<?php

include_once "Circle.php";
class Cylinder extends Circle
{
    protected $height;

    public function __construct($color, $radius,$height)
    {
        parent::__construct($color, $radius);
        $this->height = $height;
    }
    function cylinderVolume(){
        return parent::circleArea() * $this->height;
    }
    function toString()
    {
        parent::toString(); // TODO: Change the autogenerated stub
        echo 'Height: '.$this->height.'<br>';
        echo 'Volume: '.$this->cylinderVolume().'<br>';
    }
}