<?php
include_once "Point.php";

class MoveablePoint extends Point
{
    protected $xSpeed;
    protected $ySpeed;

    public function __construct($x, $y,$xSpeed,$ySpeed)
    {
        parent::__construct($x, $y);
        $this->xSpeed = $xSpeed;
        $this->ySpeed = $ySpeed;
    }

    /**
     * @return mixed
     */
    public function getXSpeed()
    {
        return $this->xSpeed;
    }

    /**
     * @param mixed $xSpeed
     */
    public function setXSpeed($xSpeed)
    {
        $this->xSpeed = $xSpeed;
    }

    /**
     * @param mixed $ySpeed
     */
    public function setYSpeed($ySpeed)
    {
        $this->ySpeed = $ySpeed;
    }

    /**
     * @return mixed
     */
    public function getYSpeed()
    {
        return $this->ySpeed;
    }
    function setSpeed($xSpeed,$ySpeed){
        $this->xSpeed = $xSpeed;
        $this->ySpeed = $ySpeed;
    }
    function getSpeed(){
        return [$this->xSpeed,$this->ySpeed];
    }
    function toString()
    {
        echo parent::toString().',Speed =('.$this->xSpeed.",".$this->ySpeed.')'; // TODO: Change the autogenerated stub
    }
    function move(){
        $this->x += $this->xSpeed;
        $this->y += $this->ySpeed;
        return $this;
    }
}